server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3306}/${DB_NAME:product}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PRODUCT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: configserver:${CONFIG_SERVER:http://config-server:9296}
order:
  service:
    url: ${ORDER_SERVICE_URL:http://order-service:8083/order}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN:http://zipkin:9411/api/v2/spans}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


