server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: PRODUCT-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: configserver:${CONFIG_SERVER:http://config-server:9296}
order:
  service:
    url: ${ORDER_SERVICE_URL:http://order-service:8083/order}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://service-registry:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true


